export enum MedicalSpecialty {
    GeneralMedicine = "General Medicine",
    FamilyMedicine = "Family Medicine",
    Pediatrics = "Pediatrics",
    InternalMedicine = "Internal Medicine",
    Cardiology = "Cardiology",
    Dermatology = "Dermatology",
    GynecologyAndObstetrics = "Gynecology & Obstetrics",
    Ophthalmology = "Ophthalmology",
    ENT = "Ear, Nose & Throat (ENT)",
    Orthopedics = "Orthopedics",
    PsychiatryAndNeurology = "Psychiatry & Neurology",
    Gastroenterology = "Gastroenterology",
    Nephrology = "Nephrology",
    Endocrinology = "Endocrinology",
    Oncology = "Oncology",
    Hematology = "Hematology",
    GeneralSurgery = "General Surgery",
    OrthopedicSurgery = "Orthopedic Surgery",
    Neurosurgery = "Neurosurgery",
    CardiothoracicSurgery = "Cardiothoracic Surgery",
    EmergencyMedicine = "Emergency Medicine",
    Dentistry = "Dentistry",
    Physiotherapy = "Physiotherapy & Rehabilitation",
    Geriatrics = "Geriatrics",
    Anesthesiology = "Anesthesiology",
    Radiology = "Radiology",
    Pathology = "Pathology & Laboratory Medicine",
    SportsMedicine = "Sports Medicine",
    PreventiveMedicine = "Preventive Medicine",
    CosmeticMedicine = "Cosmetic Medicine"
  }
  